name: Build Android APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make emscripten
        sudo sysctl fs.inotify.max_user_watches=524288

    - name: Install Node dependencies
      run: |
        export LIBRE_BUILD=true
        export JITSI_SERVER_URL="${{ secrets.JITSI_SERVER_URL }}"
        export JITSI_PRESET_ROOMS_URLS="${{ vars.JITSI_PRESET_ROOMS_URLS }}"
        npm install --build-from-source

    - name: Clone matrix-olm
      run: |
        git clone https://gitlab.matrix.org/matrix-org/olm.git matrix-olm
        cd matrix-olm
        git checkout 3.2.3

    - name: Prepare Android build
      run: |
        cd android/app
        # Remove Google services and Firebase dependencies
        sed -i -e '/if (googleServicesEnabled) {/,+2d' -e '/firebase/d' -e '/gms/d' ../build.gradle build.gradle
        sed -i -e '/targetSdkVersion/auseExoplayerIMA = false' -e '/targetSdkVersion/aRNVUseExoplayerIMA = false' ../build.gradle
        sed -i -e 's/libreBuild =.*$/libreBuild = true/g' ../build.gradle
        sed -i -e '/play-services-auth/d' build.gradle

        # Remove Google Play Services from dependencies
        sed -i -e '/play-services/d' ../../node_modules/react-native-device-info/android/build.gradle || true
        sed -i -e '/installReferrerVersion/,+11d' ../../node_modules/react-native-device-info/android/build.gradle || true
        sed -E -i 's/^.*google.*play.*services.*$//g' ../../node_modules/@react-native-google-signin/google-signin/android/build.gradle || true
        sed -i -e '/extension-ima/d' ../../node_modules/react-native-video/android/build.gradle || true
        sed -i -e '/amplitude/d' -e '/giphy/d' -e '/google-signin/d' ../settings.gradle || true

    - name: Build matrix-olm
      run: |
        cd matrix-olm
        sed -i -e 's/Wno-error=closure//' -e 's/--closure 1//' Makefile
        make -j$(nproc) js
        cp -f javascript/olm.wasm ../node_modules/@matrix-org/olm/

    - name: Build React Native bundle
      run: |
        mkdir -p android/app/src/main/assets
        npx react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

    - name: Build APK
      run: |
        cd android
        export LIBRE_BUILD=true
        export JITSI_SERVER_URL="${{ secrets.JITSI_SERVER_URL }}"
        export JITSI_PRESET_ROOMS_URLS="${{ vars.JITSI_PRESET_ROOMS_URLS }}"
        ./gradlew assemble${{ matrix.build_type == 'debug' && 'Debug' || 'Release' }}
        ls -la app/build/outputs/apk/${{ matrix.build_type }}/ || echo "${{ matrix.build_type }} APK not found"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: hashFiles('android/app/build/outputs/apk/${{ matrix.build_type }}/*.apk') != ''
      with:
        name: jitsi-meet-${{ matrix.build_type }}
        path: android/app/build/outputs/apk/${{ matrix.build_type }}/*.apk

